### ISSUE TITLE
Descrizione

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/cai#1]
# NON SCRIVERE CODICE PER IL MOMENTO

![es5_32_33](https://cloud.githubusercontent.com/assets/3002194/15793941/8151fdfe-29e7-11e6-8b64-4a383fd7e983.png)

**Comment by FabioZTessitore** [comment]
da una prima lettura del problema, secondo te di quali moduli abbiamo bisogno?

**Comment by TeoColuccio** [comment]
Uno domanda e un altro risposta

**Comment by FabioZTessitore** [comment]
forse stai pensando alle funzioni. Ho chiesto quali moduli

**Comment by TeoColuccio** [comment]
Un random sicuro e poi confrontiamo il risultato stesso nel main

**Comment by FabioZTessitore** [comment]
sul modulo random concordo. Apri tu stesso una issue "random" e cerchiamo di capire di quali funzioni sarà composto.

Altri moduli?

**Comment by TeoColuccio** [comment]
Eh un altro modulo è superfluo.. Possiamo fare un modulo che confronta il risultato e da una risposta

**Comment by FabioZTessitore** [comment]
quando pensi ai moduli pensa sempre a qualcosa che potresti riutilizzare in un altro programma. Così come il modulo random ti potrebbe servire per estrarre numeri, possiamo pensare di creare un modulo "cai" che si occupa almeno di fornire le risposte e poi vediamo se serve altro. Apri una issue "cai"

**Comment by TeoColuccio** [comment]
Ok

**Comment by FabioZTessitore** [comment]
la issue "cai" non l'hai più aperta

**Comment by FabioZTessitore** [comment]
manca esercizio 5.33

**Comment by TeoColuccio** [comment]
Ho caricato una cartella nuova

**Comment by FabioZTessitore** [comment]
L'ho vista la cartella. È proprio nuova haha non c'è niente

Il giovedì 29 settembre 2016, Teodoro notifications@github.com ha scritto:
