### ISSUE TITLE
versione python

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/cai#10]
vai. questo è l'esercizio 5.44

**Comment by TeoColuccio** [comment]
Ok sto leggendo come usare il modulo random in python.. Più o meno è la
stessa cosa

2016-10-31 11:02 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by TeoColuccio** [comment]
Lo 'switch' che in pyhton è assente lo sostituisco con dei semplici elif..

2016-10-31 11:09 GMT+01:00 Teodoro Coluccio teodoro.coluccio@gmail.com:

**Comment by TeoColuccio** [comment]
Non c'è un modo per evitare che se premo invio per sbaglio, senza aver
digitato alcuna cifra, non termina l'esecuzione?

2016-10-31 11:25 GMT+01:00 Teodoro Coluccio teodoro.coluccio@gmail.com:

**Comment by FabioZTessitore** [comment]
ho caricato una versione che risolve parzialmente il problema.
Invece di input usa raw_input perché input automaticamente cerca di convertire in intero, mentre raw_input no e ti permette di fare un controllo. Però se metti una stringa la conversione poi fallisce lo stesso. Devi aspettare, quando faremo le eccezioni imparerai a gestire bene la cosa

**Comment by TeoColuccio** [comment]
Ottimo.
Che altri tipi di input ci sono?
- input(): cerca di convertire in intero
- raw_input() che prende un input grezzo
- altro?...

2016-10-31 12:38 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
non ne conosco altri

**Comment by TeoColuccio** [comment]
Ok ma quindi una stringa con input() da errore?

2016-10-31 12:42 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
di perché cerca di convertirla

**Comment by TeoColuccio** [comment]
Ok credo che si può chiudere anche questa issue..
