### ISSUE TITLE
modulo random

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/cai#11]
in python non è necessario chiamare la funzione seed() del modulo random

**Comment by TeoColuccio** [comment]
Altissimo livello.. Poi in randint(min, max) il max ho notato che lo
comprende

2016-10-31 11:33 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
esatto. infatti se guardi l'help della funzione randrange() ti spiega che è meglio usare questa proprio perché randint non si comporta in modo standard

**Comment by TeoColuccio** [comment]
Randrange se non metto il terzo argomento che sarebbe l'incremento lo
considera 1 di default?

Il giorno 31 ottobre 2016 11:40, Fabio Z Tessitore <notifications@github.com

**Comment by FabioZTessitore** [comment]
si si, c'è scritto `step=1`

**Comment by FabioZTessitore** [comment]
bene, a questo punto dovresti esserti reso conto che nel modulo myrandom hai solo una funzione e che fa solo una chiamata a randrange. In altre parole le stai solo cambiando nome.
Conclusione: in python non è necessario che ti crei un modulo random. Quello già fatto va benissimo (batterie incluse)

**Comment by TeoColuccio** [comment]
Ok ma per curiosità dove le vedete queste info? Io su docs.python.org

2016-10-31 12:12 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
```
$ python
>>> import random
>>> dir(random)
...
>>> help(random.randrange)
```

**Comment by TeoColuccio** [comment]
Ok grazie

2016-10-31 12:20 GMT+01:00 Fabio Z Tessitore notifications@github.com:
