### ISSUE TITLE
es 5.44

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/cai#13]
# parte vecchia
![es5_32_33](https://cloud.githubusercontent.com/assets/3002194/19853057/3296735c-9f67-11e6-9eee-b8df13f91f81.png)
![es5_34](https://cloud.githubusercontent.com/assets/3002194/19853061/36d3e6fc-9f67-11e6-9890-94e41bddd6e7.png)
# parte nuova
![es5_44](https://cloud.githubusercontent.com/assets/3002194/19853064/3a2d13a0-9f67-11e6-94c7-946f0ba86f89.png)

**Comment by FabioZTessitore** [comment]
lo vedi che il codice nei vari casi è lo stesso?

**Comment by TeoColuccio** [comment]
Si cambia solo l'estrazione

**Comment by FabioZTessitore** [comment]
appunto. E ti sembra il caso di scrivere tre volte lo stesso codice?

**Comment by TeoColuccio** [comment]
Ovviamente no, faccio una funzione... (Dopo pranzo..)

**Comment by FabioZTessitore** [comment]
puoi mettere nell'if solo l'estrazione dei numeri

**Comment by TeoColuccio** [comment]
Non riesco a gestire la variabile esatte. Così come ho fatto la passa azzerata ogni volta. Magari se usassi il passaggio per riferimento...

**Comment by FabioZTessitore** [comment]
hai avuto l'intuizione di fare `return esatte`, devi solo proseguire ...`esatte = cai_play(a, b, esatte)`

**Comment by TeoColuccio** [comment]
Ah già.. Però ora per fare le opzioni è un casino

**Comment by FabioZTessitore** [comment]
devi trovare una soluzione ... haha

ps. continui a fare tre volte lo stesso codice nel main. Ti avevo detto di fare l'if solo per l'estrazione dei numeri, poi il resto resta uguale

**Comment by TeoColuccio** [comment]
E che ci sta in più? Il while?

**Comment by FabioZTessitore** [comment]
## Livello 1

```
if livello == 1:
    while conta < 10:
        a = cai_extract()
        b = cai_extract()
        cai_play(a, b, esatte)
        conta += 1
```

## Livello 2

```
elif livello == 2:
    while conta < 10:
        a = cai_extract_livello_2()
        b = cai_extract_livello_2()
        cai_play(a, b, esatte)
        conta += 1
```

## Livello 3

```
elif livello == 3:
    while conta < 10:
        a = cai_extract_livello_3()
        b = cai_extract_livello_3()
        cai_play(a, b, esatte)
        conta += 1
```

Trova le differenze haha

**Comment by TeoColuccio** [comment]
Cambia solo l'estrazione, ma il ciclo lo devo rimanere per forza..

**Comment by Teodoro777** [comment]
L'estrazione..

**Comment by TeoColuccio** [comment]
Prof e mo l'ultima scelta dell'opzione?

**Comment by FabioZTessitore** [comment]
Hai la soluzione già fatta e non la vedi

Il venerdì 4 novembre 2016, Teodoro notifications@github.com ha scritto:

**Comment by TeoColuccio** [comment]
Posso usare una chiamata ricorsiva?

**Comment by TeoColuccio** [comment]
No perchè quando la funzione muore, con essa se ne va la variabile "risposta" e quindi non posso controllare l'esito..

**Comment by FabioZTessitore** [comment]
Sarebbe bello se usassi una chiamata ricorsiva

Il venerdì 4 novembre 2016, Teodoro notifications@github.com ha scritto:
