### ISSUE TITLE
Modulo random

### ISSUE THREAD

**Issue by TeoColuccio** [Teodoro777/cai#2]
Creare il modulo random e le sue funzioni: inizializzazione del seme; estrarre 2 numeri casuali, moltiplicarli e calcolare il risultato.

**Comment by TeoColuccio** [comment]
Ho fatto un abbozzo veloce.

**Comment by FabioZTessitore** [comment]
avevo detto di non scrivere codice ... e come previsto hai scritto solo fesserie

**Comment by FabioZTessitore** [comment]
ricominciamo. Il modulo random è responsabile di ... ?

**Comment by TeoColuccio** [comment]
Estrarre 2 numeri casuali

**Comment by FabioZTessitore** [comment]
più o meno. Ricorda che il modulo è qualcosa di riutilizabile in altri programmi.
Quindi come dicevi prima sarà responsabile dell'inizializzazione del seme e sarà responsabile dell'estrazione di _un_ numero casuale.

Tieni presente che il modulo random non ne sa (e non ne deve sapere) niente del programma che stai facendo

**Comment by TeoColuccio** [comment]
Ah sì c'è anche l'inizializzazione del seme

**Comment by FabioZTessitore** [comment]
decidiamo i prototipi delle funzioni

**Comment by TeoColuccio** [comment]
random_init() e random_extraction()

**Comment by FabioZTessitore** [comment]
random_init() te la passo.
l'altra no. In ogni caso devi specificare i parametri e dire cosa ci si aspetta che facciano

**Comment by TeoColuccio** [comment]
random_init() non vuole nulla come parametro e inizializza il seme;
random_extraction() potrebbe avere come parametri un min e un max.

**Comment by FabioZTessitore** [comment]
va bene.
ma visto che siamo programmatori che ti costa scrivere i prototipi?

**Comment by TeoColuccio** [comment]
Mo avete detto niente codice! ahah faccio subito

2016-06-07 22:34 GMT+02:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
qua.

**Comment by TeoColuccio** [comment]
Ah ok 
random_init();
random_extract(int min, int max);

**Comment by FabioZTessitore** [comment]
ok. crea solo il file random.h
Per il momento niente implementazione

**Comment by FabioZTessitore** [comment]
ps eppure hai mancato i tipi di ritorno hahaha

**Comment by TeoColuccio** [comment]
Ahahah 
void random_init();
int random_extract(int min, int max);
