### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/cai#4]

**Comment by FabioZTessitore** [comment]
- [ ] main.c dipende da cai.h
- [ ] random.c dipende da random.h
- [ ] cai.c dipende da cai.h e random.h

**Comment by FabioZTessitore** [comment]
non si fa così

quando scrivi una regola, il nome che metti a sinistra è il target, cioè quello che vuoi generare

**Comment by TeoColuccio** [comment]
No non ho capito, in altri programmi non abbiamo messo i file .h nel Makefile

**Comment by FabioZTessitore** [comment]
non volevo complicarteli troppo, però meglio metterli

**Comment by TeoColuccio** [comment]
Quindi come scrivo?

**Comment by FabioZTessitore** [comment]
``` makefile
target: deps
    rule
```

target: quello che vuoi ottenere
deps: da chi dipende
rule: la regola di compilazione

**Comment by TeoColuccio** [comment]
Sì ma dobbiamo generare un file .o non un file .c

**Comment by FabioZTessitore** [comment]
appunto per questo il Makefile che hai scritto è sbagliato

**Comment by FabioZTessitore** [comment]
main.o NON dipende da cai.c
