### ISSUE TITLE
Cai

### ISSUE THREAD

**Issue by TeoColuccio** [Teodoro777/cai#5]

**Comment by FabioZTessitore** [comment]
qui dobbiamo capire di cosa è responsabile il modulo "cai".

**Comment by TeoColuccio** [comment]
Cai calcola la moltiplicazione da chiedere

**Comment by FabioZTessitore** [comment]
quasi

**Comment by TeoColuccio** [comment]
Moltiplica 2 numeri ahah

**Comment by FabioZTessitore** [comment]
tirendi conto da solo che la moltiplicazione si fa con un *

**Comment by TeoColuccio** [comment]
E poi controlla se il risulato è uguale al numero che inserirà l'utente

**Comment by FabioZTessitore** [comment]
e si fa con ==

**Comment by TeoColuccio** [comment]
Eh ma tutto il programma è facile... In base al controllo da una risposta

**Comment by FabioZTessitore** [comment]
ma il programma deve fare _alcune_ cose, quali sono?

**Comment by TeoColuccio** [comment]
Deve dare la risposta di un errore fin quando l'utente non la indovina.

**Comment by FabioZTessitore** [comment]
1) dare messaggio di errore, ok
altro?

**Comment by TeoColuccio** [comment]
Fa riprovare, quindi un ciclo

**Comment by FabioZTessitore** [comment]
ma no

**Comment by TeoColuccio** [comment]
Eh che ne so

**Comment by FabioZTessitore** [comment]
allora riposati e poi ci pensi

**Comment by TeoColuccio** [comment]
Ahah ok

**Comment by TeoColuccio** [comment]
Questo deve fare il programma e in particolare il modulo cai: Moltiplica i
due numeri casuali; confronta la risposta con il risultato e se è corretta
dice una cosa altrimenti ne dice un'altra e fa riprovare..

2016-06-07 23:41 GMT+02:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
Ricapitoliamo:

la moltiplicazione si fa con *
il confronto con ==

rimane valido il concetto che si deve dire una cosa se la risposta è corretta e un'altra se la risposta è errata.

Per trovare le altre cose di cui è responsabile il modulo cai ricorda che il modulo random è un modulo di supporto che non sa niente del programma.

**Comment by TeoColuccio** [comment]
Ma questo è il programma, non c'è nient'altro da fare..

**Comment by FabioZTessitore** [comment]
indizio:

nel main non devi usare il modulo random

**Comment by TeoColuccio** [comment]
Vabbè random deve solo pescare i 2 numeri, poi se la vede cai a moltiplicare ecc.

**Comment by FabioZTessitore** [comment]
non ci capiamo. Nel main non userai random, quindi come li peschi i numeri?

**Comment by TeoColuccio** [comment]
Li pesco in cai, questo intendevo dire..

**Comment by FabioZTessitore** [comment]
appunto

quindi ricapitolando serve:

1) una funzione di inizializzazione del modulo
2) una funzione per l'estrazione di un numero (secondo i criteri del programma)
3) una funzione che restituisce un messaggio di risposta esatta
4) una funzione che restituisce un messaggio di risposta errata

**Comment by TeoColuccio** [comment]
Per inizializzazione che intendete?

**Comment by FabioZTessitore** [comment]
tutte le operazioni necessarie affinché il modulo funzioni correttamente

inizia a scrivere i prototipi

**Comment by TeoColuccio** [comment]
1) void init_cai()
2) int cai_extract()
3) char\* cai_true()
4) char\* cai_false()

Anche se non ho ancora capito a che serve init()...

**Comment by FabioZTessitore** [comment]
init_cai la facciamo diventare cai_init

poi inizia a scrivere i file random.h e cai.h (ma non i file .c)

infine prova a scrivere un main.c che implementa il programma
(scrivendo il main dovrebbero chiarirsi i dubbi)

**Comment by FabioZTessitore** [comment]
non viene mai estratto il 9
