### ISSUE TITLE
cai.c

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/cai#6]
Puoi cominciare a sviluppare le funzioni di cai

**Comment by FabioZTessitore** [comment]
cai.c non sa dove sono i prototipi delle funzioni che definisce

**Comment by TeoColuccio** [comment]
Ma come faceva a funzionare?

**Comment by TeoColuccio** [comment]
Ma come funzionava? C'è una spiegazione?

**Comment by FabioZTessitore** [comment]
i prototipi di funzione servono, ma in base alle opzioni che passi al compilatore è una mancanza che a volte viene perdonata. Non è una buona pratica non metterli però
